version: '3.7'

services:
  iris:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    image: iris-fhir-interop:iris
    container_name: iris
    command: --check-caps false
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app

  webserver:
    hostname: webserver
    build:
      context: webserver
      dockerfile: Dockerfile
    image: iris-fhir-interop:webserver
    container_name: webserver
    init: true
    depends_on:
      - iris
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./webserver:/webserver
    environment:
    - ISC_DATA_DIRECTORY=/webserver